language: elixir

matrix:
  include:
    - elixir: '1.5.3'
      otp_release: '18.0'
    - elixir: '1.6.4'
      otp_release: '18.0'
    - elixir: '1.7.1'
      otp_release: '20.0'
    - elixir: '1.7.1'
      otp_release: '21.0'

addons:
  postgresql: '9.5'

services:
  - postgresql

before_script:
  - psql -c 'create database rihanna_db;' -U postgres -h localhost

script:
  - mix test
